# Form implementation generated from reading ui file 'BinanceTracker.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import json
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtNetwork import QNetworkAccessManager, QNetworkRequest
from data_loader import render_data

class Ui_BinanceTracker(object):
    def setupUi(self, BinanceTracker):
        BinanceTracker.setObjectName("BinanceTracker")
        BinanceTracker.resize(640, 480)
        BinanceTracker.setStyleSheet("QPushButton {\n"
"    height: 50px; \n"
"    width: 120px;\n"
"    \n"
"    font: 9pt \"Segoe UI\";\n"
"}\n"
"\n"
"QLineEdit {\n"
"    height: 50px; \n"
"    width: 120px; \n"
"    \n"
"    font: 9pt \"Segoe UI\";\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=BinanceTracker)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(parent=self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_5.addWidget(self.lineEdit_2, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_5.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_5.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.tab_2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        BinanceTracker.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=BinanceTracker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        BinanceTracker.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=BinanceTracker)
        self.statusbar.setObjectName("statusbar")
        BinanceTracker.setStatusBar(self.statusbar)

        self.retranslateUi(BinanceTracker)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BinanceTracker)

        # Render tickers
        render_data(self.tableWidget_2, {'BTC': 0.34112, 'UTC': 4.6552})

    def retranslateUi(self, BinanceTracker):
        _translate = QtCore.QCoreApplication.translate
        BinanceTracker.setWindowTitle(_translate("BinanceTracker", "BinanceTracker V1"))
        self.groupBox.setTitle(_translate("BinanceTracker", "Операции"))
        self.pushButton.setText(_translate("BinanceTracker", "Добавить операцию"))
        self.lineEdit.setPlaceholderText(_translate("BinanceTracker", "Добавьте отслеживаемую функцию, например: ETHBTC*BNBBTC     "))
        self.pushButton_3.setText(_translate("BinanceTracker", "Удалить операцию"))
        self.groupBox_2.setTitle(_translate("BinanceTracker", "Настройки трекера"))
        self.lineEdit_2.setPlaceholderText(_translate("BinanceTracker", "Минимальное значение:"))
        self.lineEdit_3.setPlaceholderText(_translate("BinanceTracker", "Максимальное значение:"))
        self.pushButton_2.setText(_translate("BinanceTracker", "Сохранить значения"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("BinanceTracker", "Отслеживаемые монеты"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("BinanceTracker", "Полный список монет"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BinanceTracker = QtWidgets.QMainWindow()
    ui = Ui_BinanceTracker()
    ui.setupUi(BinanceTracker)
    BinanceTracker.show()
    sys.exit(app.exec())
